[build]
  base = "/"
  publish = "out"
  command = "yarn next build --debug"
  functions = "functions/src"
  edge_functions = "functions/edge"

[build.environment]
  NODE_VERSION = "20"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"
  UV_THREADPOOL_SIZE = 16
  NETLIFY_NEXT_PLUGIN_SKIP = true

[dev]
  port = 8888
  framework = "#static"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  
[functions]  
  node_bundler = "esbuild"
  included_files = [
    "specification.json",
  ]
  external_node_modules = [
    "@oceanics/functions",
    "neo4j-driver",
    "@logtail/js"
  ]
