[build]
  base = "/"
  publish = "out"
  command = "yarn next build --debug"
  functions = "functions/src"
  edge_functions = "functions/edge"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY_NEXT_PLUGIN_SKIP = true

[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  
[functions]  
  node_bundler = "esbuild"
  included_files = [
    "specification.json"
  ]
  external_node_modules = [
    "@oceanics/functions",
    "neo4j-driver"
  ]
