query {
    bathysphere: allBathysphereYaml(filter: {
        kind: {
            eq: "Things"
        } 
    }) {
        things: nodes {
            apiVersion
            metadata {
                icon
            }
            kind
            spec {
                name
                description
                properties {
                    home
                    capacity
                    meters {
                        name
                        max
                        value
                        high
                        low
                    }
                }
            }
        }
    }
    team: allBathysphereYaml(
        filter: {
            kind: { eq: "Agents" }
        }
    ) {
        team: nodes {
            spec { name }
        }   
    }
    locations: allBathysphereYaml(
        filter: {
            kind: { eq: "Locations" }
            metadata: {
                fictional: { eq: true }
            }
        }
    ) {
        locations: nodes {
            kind
            metadata {
                fictional
                home
                icon
                capacity
            }
            spec { name }
        }   
    }
    tasks: allBathysphereYaml(
        filter: {
            kind: { eq: "Tasks" }
        }
    ) {
        tasksByLocation: group(field: metadata___Locations___name) {
            location: fieldValue
            nodes { 
                spec { name }
            }
        }  
    }
}